#!/usr/bin/perl
#
#
#
use warnings;
use strict;

my $fact = 36;
sub digital_root_readable($) {

    my $number = shift;
    while ($number > 9) {
        my $total;
        for my $digit (split(//,$number)) {
            $total += $digit
        }
        $number=$total;
    }

    return $number;

}

sub digital_root($) {

    my $n = shift;
    $n=($n%9?$n%9:9);
    return $n;

}

my $colour = {
    1 => 'one',
    2 => 'two',
    3 => 'three',
    4 => 'four',
    5 => 'five',
    6 => 'six',
    7 => 'seven',
    8 => 'eight',
    9 => 'nine'
};

print qq~
<link rel="stylesheet" title="Colour" href="colours.css" type="text/css" />
<table>\n~;

for my $x ( 1 .. $fact ) {

    print "<tr>\n";

    for my $y ( 1 .. $fact ) {

        my $prod = $x * $y;

        my $root = digital_root($prod);

        printf qq~ <td class="%s"> %3d </td> ~, $colour->{$root}, $prod;

    }

    print "\n</tr>\n";

}

print "</table>\n";


