#!/usr/bin/perl
#
# Print random table for practicing times tables
#
use warnings;
use strict;

my (@tab);

my $max = 12;
$max = shift if @ARGV;
die "Usage: $0 NUMBER\n" if $max !~ /^\d+$/;

for my $a ( 1 .. $max ) {

    for my $b ( 1 .. $max ) {

        push @tab, sprintf "%2dx%-2d", $a, $b;

    }

}

for my $a ( 1 .. $max ) {

    for my $b ( 1 .. $max ) {

        printf " %s", splice @tab, int(rand($#tab+1)), 1;

    }

    print $/;

}

